# Generated by Django 3.2.6 on 2021-08-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_test_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='TestModel',
        ),
    ]
